version: '3.1'
services:
  proxy:
    image: mattes/rotating-proxy
    environment:
      - tors=25
  crawler:
    image: vanuan/data-gov-ua-crawler
    environment:
      - PROXY_URL=http://proxy:5566
      - DELAY=10000
      - CONCURRENCY=1
    volumes:
      - /data:/data
    working_dir: /src
    command: sh -c 'yarn install && node app.js --cron "0 10 0 * * 6" --run'
    depends_on:
      - proxy
