version: '3.1'
services:
  proxy:
    image: mattes/rotating-proxy
    environment:
      - tors=25
  rethinkdb:
    image: 'vanuan/rethinkdb-alpine'
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /data/rethinkdb:/data
  crawler:
    image: vanuan/data-gov-ua-crawler
    environment:
      - PROXY_URL=http://proxy:5566
      - DELAY=10000
      - CONCURRENCY=1
      - NODE_ENV=production
    volumes:
      - /data:/data
    working_dir: /src
    command: sh -c 'yarn install && node crawlInitial'
    depends_on:
      - proxy
