version: '2'
services:
  proxy:
    image: mattes/rotating-proxy
    ports:
      - "5566:5566"
      - "4444:4444"
    environment:
      - tors=25
  crawler:
    build: ./app/build
    volumes:
      - ./app:/src
      - ./data:/data
      - ./tmp_yarn_cache:/usr/local/share/.cache/yarn
    working_dir: /src
    command: sh -c 'yarn install && node app.js --cron "0 10 0 * * 6" --run'
    depends_on:
      - proxy
    environment:
      - http_proxy=http://proxy:5566/
  elasticsearch:
    image: elasticsearch:5.1.1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_config:/usr/share/elasticsearch/config
      - elasticsearch_data:/usr/share/elasticsearch/data
  logstash:
    image: logstash:5.1.1
    volumes:
      - ./logstash:/crawler/logstash
      - ./data:/crawler/data
    command: bash -c "env GEM_HOME=/usr/share/logstash/vendor/bundle/jruby/1.9 /usr/share/logstash/vendor/jruby/bin/jruby -S gem install geocoder -v 1.4.1 && echo 'gem \"geocoder\", \"~> 1.4.1\"' >> /usr/share/logstash/Gemfile && logstash -f /crawler/logstash/metadata.conf"
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:5.1.1
    ports:
      - "5601:5601"
    volumes:
      - kibana_config:/etc/kibana/
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_config: {}
  elasticsearch_data: {}
  kibana_config: {}
